spring:
  application:
    name: hello-server
  freemarker:
    prefer-file-system-access: false
server:
  port: 8180
  address: 192.168.43.199
  servlet:
#    path: /*
    context-path: /hello-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.43.199:8080/eureka-server/eureka
  instance:
    hostname: 192.168.43.199
logging:
  level:
    org.springframework.web: DEBUG